env:
  FLUTTER_VERSION: "3.32.5"

cache:
  paths:
    - "flutter-take-two"
  size: "20g"

agents:
  queue: "macos"

steps:
  - label: ":package: Install Dependencies"
    command: |
      source ./setup_flutter.sh
      flutter pub get

  - label: ":test_tube: Run Tests"
    command: |
      source ./setup_flutter.sh
      flutter test

  - label: ":wrench: Build macOS App"
    command: |
      source ./setup_flutter.sh
      flutter build macos
